
collections:
  writeups:
    output: true

defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: ctf

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  


